/*
 * UOR Prime Structure FFI - Initialization Module
 *
 * This module provides initialization and finalization functions for the
 * UOR Prime Structure library. It manages the Lean runtime lifecycle and
 * ensures all required modules are properly initialized.
 *
 * The initialization order is important:
 * 1. Lean runtime module (base system)
 * 2. Prime Structure (mathematical constants)
 * 3. Atlas Core (boundary structure)
 * 4. FFI CAPI (exported functions)
 */

#include <stdint.h>

#include <lean/lean.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Lean runtime initialization - defined in leanshared */
extern void lean_initialize(void);
extern void lean_initialize_runtime_module(void);
extern void lean_io_mark_end_initialization(void);

/*
 * External module initializers generated by Lean.
 * These functions are created automatically when building the Lean modules.
 */
extern lean_object *initialize_UOR_Prime_Structure(uint8_t builtin,
                                                   lean_object *);
extern lean_object *initialize_UOR_Atlas_Core(uint8_t builtin, lean_object *);
extern lean_object *initialize_UOR_FFI_CAPI(uint8_t builtin, lean_object *);

/**
 * Initialize the UOR library and all dependent modules.
 *
 * This function must be called once before using any other UOR functions.
 * It initializes the Lean runtime and all UOR modules in the correct order.
 *
 * @param resv Reserved parameter for future use (pass 0)
 */
void lean_initialize_uor(uintptr_t resv) {
  /* Initialize the Lean runtime first */
  lean_initialize();
  lean_initialize_runtime_module();

  /* Initialize UOR modules - pass 1 for builtin, NULL for world */
  lean_object *io_res;
  io_res = initialize_UOR_Prime_Structure(1, lean_io_mk_world());
  if (lean_io_result_is_error(io_res)) {
    lean_io_result_show_error(io_res);
    lean_dec(io_res);
    return;
  }
  lean_dec(io_res);

  io_res = initialize_UOR_Atlas_Core(1, lean_io_mk_world());
  if (lean_io_result_is_error(io_res)) {
    lean_io_result_show_error(io_res);
    lean_dec(io_res);
    return;
  }
  lean_dec(io_res);

  io_res = initialize_UOR_FFI_CAPI(1, lean_io_mk_world());
  if (lean_io_result_is_error(io_res)) {
    lean_io_result_show_error(io_res);
    lean_dec(io_res);
    return;
  }
  lean_dec(io_res);

  /* Mark end of initialization */
  lean_io_mark_end_initialization();
}

/**
 * Finalize the UOR library and clean up resources.
 *
 * This function should be called at process shutdown to properly clean up
 * the Lean runtime. It's optional but recommended for clean shutdown.
 */
void lean_finalize_uor(void) {
  /* No explicit finalization needed - Lean runtime handles cleanup */
}

#ifdef __cplusplus
}
#endif